---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssv-faucet-bot
  name: ssv-faucet-bot
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-faucet-bot
  template:
    metadata:
      labels:
        app: ssv-faucet-bot
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SINGER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: singer_private_key

            - name: SIGNER_OWNER_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: signer_owner_address

            - name: SSV_NETWORKS
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: ssv_networks

            - name: SSV_EXPLORER_URL
              value: "http://explorer-center-api-v2-svc.explorer:5000"

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
